"""Briccolani (1800), *Serie delle Sagre Immagini di Maria Vergine coronate* — transcription.

Vincenzo Briccolani, *Descrizione della sacrosanta Basilica Vaticana ... con l'Elenco delle
Consagrazioni degli Altari, Catalogo delle Reliquie, e Serie delle Coronazioni delle Immagini di
Maria Vergine fatte dal reverendissimo Capitolo Vaticano*, edizione seconda, Roma, Salomoni, 1800,
pp. 144-161. Transcribed from the Getty Research Institute copy on the Internet Archive
(gri_33125011212400, PDF pp. 158-175) on 14 September 2026, page by page against the scan, with the
text layer as a first draft. The 1816 third edition omits the list.

The list is the earliest PRINTED register of the practice: year by year, every image the Chapter
had crowned from 1631 to 1791 (plus one of 1793 added at the end), first Rome only, then — after a
printer's ornament between 1679 and 1681 — the whole of Italy and abroad. It gives years only, no
day or month, and no archival reference. Twelve entries are separate crowns for the Child
("Bambino Gesù") of an image already crowned. Spelling is Briccolani's; obvious misprints are kept
as printed and noted (1688 for 1788; "Cassoli" for Carsoli).

Output: data/briccolani-1800-serie.json
"""
import json,pathlib
REPO=pathlib.Path(__file__).resolve().parent.parent

# (page, year_printed, year, kind, text_as_printed, locality, church_or_place, country, notes)
# kind: 'image' = the image; 'child' = a crown for the Bambino Gesù of an image already crowned
R='Rome'; I='Italy'
ROWS=[
 (144,'1631',1631,'image',"Santa Maria della Febre, nella Sacristia della Basilica Vaticana","Rome, Vatican Basilica (sacristy)","Sacristia della Basilica Vaticana",I,None),
 (144,'1632',1632,'image',"Santa Maria de' Monti","Rome, Santa Maria ai Monti","Santa Maria de' Monti",I,None),
 (144,'1633',1633,'image',"Santa Maria della Vittoria","Rome, Santa Maria della Vittoria","Santa Maria della Vittoria",I,None),
 (144,'1634',1634,'image',"Santa Maria col Bambino Gesù di via Cupa in Santa Maria in Trastevere","Rome, Santa Maria in Trastevere","Santa Maria in Trastevere (Madonna di Strada Cupa)",I,None),
 (144,None,1634,'image',"Santa Maria della Pace","Rome, Santa Maria della Pace","Santa Maria della Pace",I,None),
 (144,None,1634,'image',"Santa Maria del Popolo","Rome, Santa Maria del Popolo","Santa Maria del Popolo",I,None),
 (144,None,1634,'image',"Santa Maria della Consolazione","Rome, Santa Maria della Consolazione","Santa Maria della Consolazione",I,None),
 (144,'1635',1635,'image',"Santa Maria della Concezione in S. Lorenzo, e Damaso","Rome, San Lorenzo in Damaso","S. Lorenzo in Damaso",I,None),
 (144,None,1635,'image',"Santa Maria Annunziata in Tor de' Specchi","Rome, Tor de' Specchi","Tor de' Specchi (Oblate di S. Francesca Romana)",I,None),
 (144,'1636',1636,'image',"Santa Maria in Araceli","Rome, Santa Maria in Aracoeli","Santa Maria in Aracoeli",I,None),
 (144,'1637',1637,'image',"Santa Maria della Pietà in S. Pietro","Rome, Vatican Basilica (Pietà)","Basilica Vaticana (Michelangelo's Pietà)",I,None),
 (145,'1638',1638,'image',"Santa Maria della Strada nella Chiesa del Gesù","Rome, Chiesa del Gesù","Chiesa del Gesù",I,None),
 (145,None,1638,'image',"Santa Maria in Santa Teresa alle quattro Fontane","Rome, Santa Teresa alle Quattro Fontane","Santa Teresa alle Quattro Fontane",I,
   "Briccolani adds after this entry: 'Le suriferite Coronazioni seguirono ancor vivente il Pio Testatore, la morte del quale seguì alli 20. d'Agosto del 1638.'"),
 (145,'1640',1640,'image',"Santa Maria del Rosario nella Chiesa di Santa Maria sopra Minerva","Rome, Santa Maria sopra Minerva","Santa Maria sopra Minerva (cappella del Rosario)",I,None),
 (145,'1641',1641,'image',"Santa Maria in S. Agostino","Rome, Sant'Agostino","Sant'Agostino",I,None),
 (145,None,1641,'image',"Santa Maria nella Chiesa de' SS. Domenico, e Sisto a Monte Magnanapoli","Rome, monastery of the Dominican nuns of San Sisto (Santi Domenico e Sisto, Magnanapoli)","SS. Domenico e Sisto a Magnanapoli (the Dominican nuns of San Sisto)",I,None),
 (145,None,1641,'image',"Santa Maria in Traspontina","Rome, Santa Maria in Traspontina","Santa Maria in Traspontina",I,None),
 (145,None,1641,'image',"Santa Maria in S. Cosimato in Trastevere","Rome, San Cosimato in Trastevere","San Cosimato in Trastevere",I,None),
 (145,'1643',1643,'image',"Santa Maria in Via Lata","Rome, Santa Maria in Via Lata","Santa Maria in Via Lata",I,None),
 (145,None,1643,'child',"Bambino Gesù della Beata Vergine della Febre nella Sacristia Vaticana","Rome, Vatican Basilica (sacristy)","Sacristia della Basilica Vaticana",I,"Crown for the Child of the Madonna della Febre (image crowned 1631)."),
 (145,None,1643,'image',"Santa Maria del Pianto","Rome, Santa Maria del Pianto","Santa Maria del Pianto",I,None),
 (145,None,1643,'image',"Santa Maria del Soccorso nella Cappella Gregoriana della Basilica Vaticana","Rome, Vatican Basilica (Cappella Gregoriana)","Cappella Gregoriana della Basilica Vaticana",I,None),
 (145,'1644',1644,'image',"Santa Maria delle Grazie a Porta Angelica","Rome, Santa Maria delle Grazie a Porta Angelica","Santa Maria delle Grazie a Porta Angelica",I,None),
 (145,None,1644,'child',"Bambino Gesù della Beata Vergine di S. Cosimato in Trastevere","Rome, San Cosimato in Trastevere","San Cosimato in Trastevere",I,"Crown for the Child (image crowned 1641)."),
 (145,None,1644,'image',"Santa Maria di Loreto in S. Salvator in Lauro","Rome, San Salvatore in Lauro","San Salvatore in Lauro",I,None),
 (146,'1645',1645,'image',"Santa Maria della Colonna nella Basilica Vaticana","Rome, Vatican Basilica (Madonna della Colonna)","Basilica Vaticana",I,None),
 (146,None,1645,'image',"Santa Maria nella Chiesa di S. Alessio","Rome, Sant'Alessio","Sant'Alessio all'Aventino",I,None),
 (146,None,1645,'child',"Bambino Gesù della Beata Vergine della Colonna in S. Pietro","Rome, Vatican Basilica (Madonna della Colonna)","Basilica Vaticana",I,"Crown for the Child (image crowned the same year)."),
 (146,None,1645,'image',"Santa Maria dentro il Monastero di S. Marta al Collegio Romano","Rome, Santa Marta al Collegio Romano","Monastero di S. Marta al Collegio Romano",I,None),
 (146,None,1645,'image',"Santa Maria de' Miracoli sulla Piazza del Popolo","Rome, Santa Maria dei Miracoli","Santa Maria dei Miracoli, Piazza del Popolo",I,None),
 (146,'1646',1646,'image',"Santa Maria in Via","Rome, Santa Maria in Via","Santa Maria in Via",I,None),
 (146,None,1646,'image',"Santa Maria della Purità in Borgo","Rome, Santa Maria della Purità in Borgo","Santa Maria della Purità in Borgo",I,None),
 (146,None,1646,'child',"Bambino Gesù della Beata Vergine di Santa Marta","Rome, Santa Marta al Collegio Romano","Monastero di S. Marta al Collegio Romano",I,"Crown for the Child (image crowned 1645)."),
 (146,None,1646,'image',"Santa Maria della Scala in Trastevere","Rome, Santa Maria della Scala (Trastevere)","Santa Maria della Scala in Trastevere",I,None),
 (146,None,1646,'child',"Bambino Gesù della Beata Vergine di S. Salvator in Lauro","Rome, San Salvatore in Lauro","San Salvatore in Lauro",I,"Crown for the Child (image crowned 1644)."),
 (146,'1647',1647,'child',"Bambino Gesù della Beata Vergine della Cappella Gregoriana in S. Pietro","Rome, Vatican Basilica (Cappella Gregoriana)","Cappella Gregoriana della Basilica Vaticana",I,"Crown for the Child of the Madonna del Soccorso (image crowned 1643)."),
 (146,None,1647,'image',"Santa Maria in Fonte presso S. Giovanni Laterano","Rome, San Giovanni in Fonte (Lateran baptistery)","San Giovanni in Fonte, presso S. Giovanni Laterano",I,None),
 (146,None,1647,'image',"Santa Maria delle Grazie nella Chiesa della Consolazione","Rome, Santa Maria delle Grazie al Foro Romano","Chiesa della Consolazione (Madonna delle Grazie)",I,None),
 (146,None,1647,'image',"Santa Maria nel Monastero de' SS. Domenico, e Sisto","Rome, Santi Domenico e Sisto (Magnanapoli), inner monastery","Monastero de' SS. Domenico e Sisto",I,"A second entry for the same community, six years after the church's image of 1641: an image inside the monastery."),
 (146,'1648',1648,'image',"Santa Maria della Misericordia in S. Giovanni de Fiorentini","Rome, San Giovanni dei Fiorentini","San Giovanni dei Fiorentini",I,None),
 (146,None,1648,'image',"Santa Maria della Salute in S. Lorenzo in Lucina","Rome, San Lorenzo in Lucina","San Lorenzo in Lucina",I,None),
 (146,'1649',1649,'image',"Santa Maria in Vallicella detta la Chiesa Nuova","Rome, Santa Maria in Vallicella","Santa Maria in Vallicella (Chiesa Nuova)",I,None),
 (147,'1650',1650,'image',"Santa Maria in S. Silvestro a Monte Cavallo","Rome, San Silvestro al Quirinale","San Silvestro a Monte Cavallo",I,None),
 (147,None,1650,'image',"Santa Maria in S. Giovannino in Campo Marzo de' PP. della Mercede","Rome, San Giovannino in Campo Marzio (Mercedarians)","San Giovannino in Campo Marzio",I,None),
 (147,None,1650,'image',"Santa Maria in Portico in Campitelli","Rome, Santa Maria in Portico in Campitelli","Santa Maria in Portico in Campitelli",I,None),
 (147,'1651',1651,'image',"Santa Maria di Costantinopoli a capo le Case","Rome, Santa Maria di Costantinopoli a Capo le Case","Santa Maria di Costantinopoli a Capo le Case",I,None),
 (147,None,1651,'child',"Bambino Gesù della Beata Vergine della Traspontina","Rome, Santa Maria in Traspontina","Santa Maria in Traspontina",I,"Crown for the Child (image crowned 1641)."),
 (147,None,1651,'image',"Santa Maria nell'Oratorio di Campitelli","Rome, Oratorio di Campitelli","Oratorio di Campitelli",I,None),
 (147,None,1651,'image',"Santa Maria in S. Cosma, e Damiano in Campo Vaccino","Rome, Santi Cosma e Damiano","SS. Cosma e Damiano in Campo Vaccino",I,None),
 (147,None,1651,'child',"Bambino Gesù della Beata Vergine del Pianto","Rome, Santa Maria del Pianto","Santa Maria del Pianto",I,"Crown for the Child (image crowned 1643)."),
 (147,None,1651,'image',"Santa Maria in S. Paolino alla Regola","Rome, San Paolino alla Regola","San Paolino alla Regola",I,None),
 (147,None,1651,'child',"Bambino Gesù della Beata Vergine della Purità in Borgo","Rome, Santa Maria della Purità in Borgo","Santa Maria della Purità in Borgo",I,"Crown for the Child (image crowned 1646)."),
 (147,'1652',1652,'image',"Santa Maria nella Chiesa di S. Anna alli Falegnami","Rome, Sant'Anna dei Falegnami","Sant'Anna dei Falegnami",I,None),
 (147,None,1652,'image',"Santa Maria ad Martires, detta la Rotonda","Rome, Pantheon (Santa Maria ad Martyres)","Santa Maria ad Martyres (Rotonda)",I,None),
 (147,'1653',1653,'image',"Santa Maria in Posterola all'Orso","Rome, Santa Maria in Posterula","Santa Maria in Posterula all'Orso",I,None),
 (147,None,1653,'image',"Santa Maria nel Portico di S. Apollinare","Rome, Sant'Apollinare (portico)","Portico di Sant'Apollinare",I,None),
 (147,None,1653,'image',"Santa Maria Liberatrice in Campo Vaccino","Rome, Santa Maria Liberatrice","Santa Maria Liberatrice in Campo Vaccino",I,None),
 (147,'1654',1654,'image',"Santa Maria nella Chiesa della Trinità de' Pellegrini","Rome, Santissima Trinità dei Pellegrini","SS. Trinità dei Pellegrini",I,None),
 (147,None,1654,'image',"Santa Maria delle Grazie in S. Salvator in Lauro","Rome, San Salvatore in Lauro","San Salvatore in Lauro",I,None),
 (148,None,1654,'child',"Bambino Gesù della Beata Vergine del Rosario in Santa Maria sopra Minerva","Rome, Santa Maria sopra Minerva","Santa Maria sopra Minerva (cappella del Rosario)",I,"Crown for the Child (image crowned 1640)."),
 (148,'1655',1655,'image',"Santa Maria in S. Spirito in Sassia","Rome, Santo Spirito in Sassia","Santo Spirito in Sassia",I,None),
 (148,None,1655,'image',"Santa Maria nella Chiesa delle Monache di Campo Marzo","Rome, Santa Maria in Campo Marzio (nuns)","Chiesa delle Monache di Campo Marzio",I,None),
 (148,None,1655,'image',"Santa Maria in S. Prasede","Rome, Santa Prassede","Santa Prassede",I,None),
 (148,'1656',1656,'image',"Santa Maria di Monserrato","Rome, Santa Maria di Monserrato","Santa Maria di Monserrato",I,None),
 (148,'1657',1657,'image',"Santa Maria dell'Orto in Trastevere","Rome, Santa Maria dell'Orto","Santa Maria dell'Orto in Trastevere",I,None),
 (148,'1658',1658,'image',"Santa Maria nella Chiesa di S. Rocco a Ripetta","Rome, San Rocco a Ripetta","San Rocco a Ripetta",I,None),
 (148,None,1658,'image',"Santa Maria nella Cappella Salviati in S. Gregorio al Monte Celio","Rome, San Gregorio al Celio (Cappella Salviati)","Cappella Salviati, San Gregorio al Celio",I,None),
 (148,None,1658,'image',"Santa Maria nell'Oratorio di S. Marcello","Rome, Oratorio del Crocifisso di San Marcello","Oratorio del SS. Crocifisso di San Marcello",I,"The oratory of the Arciconfraternita del SS. Crocifisso at San Marcello — not the Servite church's Madonna dei Sette Dolori, crowned 1695."),
 (148,'1659',1659,'image',"Santa Maria in S. Martino a' Monti","Rome, San Martino ai Monti","San Martino ai Monti",I,None),
 (148,None,1659,'image',"Santa Maria della Clemenza in Santa Maria in Trastevere","Rome, Santa Maria in Trastevere (Madonna della Clemenza)","Santa Maria in Trastevere",I,None),
 (148,None,1659,'image',"Santa Maria di Monte Santo sulla piazza del Popolo","Rome, Santa Maria di Montesanto","Santa Maria di Montesanto, Piazza del Popolo",I,None),
 (148,None,1659,'image',"Santa Maria nella Chiesa di S. Giacomo degl'Incurabili","Rome, San Giacomo degli Incurabili","San Giacomo degli Incurabili (in Augusta)",I,None),
 (148,'1660',1660,'image',"Santa Maria di Loreto a Colonna Trajana","Rome, Santa Maria di Loreto (Colonna Traiana)","Santa Maria di Loreto al Foro Traiano",I,None),
 (148,'1661',1661,'image',"Santa Maria dell'Orazione nella Chiesa della Morte a strada Giulia","Rome, Santa Maria dell'Orazione e Morte","Santa Maria dell'Orazione e Morte, via Giulia",I,None),
 (148,None,1661,'image',"Santa Maria in S. Giovanni decollato","Rome, San Giovanni Decollato","San Giovanni Decollato",I,None),
 (148,'1662',1662,'image',"Santa Maria in S. Francesca Romana in Campo Vaccino","Rome, Santa Francesca Romana","Santa Francesca Romana (Santa Maria Nova)",I,None),
 (149,None,1662,'image',"Santa Maria in S. Grisogono in Trastevere","Rome, San Crisogono","San Crisogono in Trastevere",I,None),
 (149,'1664',1664,'image',"Santa Maria in S. Giacomo Scosciacavalli","Rome, San Giacomo Scossacavalli","San Giacomo Scossacavalli (demolished 1937)",I,None),
 (149,None,1664,'image',"Santa Maria in S. Giovanni Calabita all'Isola","Rome, San Giovanni Calibita","San Giovanni Calibita, Isola Tiberina",I,None),
 (149,'1665',1665,'image',"Santa Maria in S. Celso in Banchi","Rome, Santi Celso e Giuliano","San Celso in Banchi",I,None),
 (149,None,1665,'image',"Santa Maria del Sole incontro alla Bocca della Verità","Rome, Santa Maria del Sole","Santa Maria del Sole (Tempio di Vesta)",I,None),
 (149,'1666',1666,'image',"Santa Maria nella Chiesa del Suffraggio","Rome, Santa Maria del Suffragio","Santa Maria del Suffragio",I,None),
 (149,None,1666,'image',"Santa Maria nella Chiesa di S. Lucia del Confalone","Rome, Santa Lucia del Gonfalone","Santa Lucia del Gonfalone",I,None),
 (149,'1667',1667,'child',"Bambino Gesù della B. V. del Popolo","Rome, Santa Maria del Popolo","Santa Maria del Popolo",I,"Crown for the Child (image crowned 1634)."),
 (149,None,1667,'child',"Bambino Gesù della B. V. de' Miracoli","Rome, Santa Maria dei Miracoli","Santa Maria dei Miracoli, Piazza del Popolo",I,"Crown for the Child (image crowned 1645)."),
 (149,None,1667,'image',"Santa Maria in S. Dionigi alle quattro Fontane","Rome, San Dionigi alle Quattro Fontane","San Dionigi alle Quattro Fontane (demolished)",I,None),
 (149,None,1667,'image',"Santa Maria in S. Lucia della Tinta","Rome, Santa Lucia della Tinta","Santa Lucia della Tinta",I,None),
 (149,'1668',1668,'image',"Santa Maria del Rosario nella Chiesa di S. Michele a Ripa","Rome, San Michele a Ripa","San Michele a Ripa",I,None),
 (149,None,1668,'image',"Santa Maria della Salute nella Chiesa della Madalena","Rome, Santa Maria Maddalena","Santa Maria Maddalena",I,None),
 (149,'1670',1670,'image',"Santa Maria della Quercia vicino a Piazza Farnese","Rome, Santa Maria della Quercia","Santa Maria della Quercia",I,None),
 (149,'1671',1671,'image',"Santa Maria in S. Biagio della Pagnotta","Rome, San Biagio della Pagnotta","San Biagio della Pagnotta",I,None),
 (149,'1672',1672,'image',"Santa Maria in Cosmedin detta la Bocca della Verità","Rome, Santa Maria in Cosmedin","Santa Maria in Cosmedin",I,None),
 (150,'1673',1673,'image',"Santa Maria nella Cappella di S. Aniceto del Palazzo Altemps","Rome, Palazzo Altemps, chapel of Sant'Aniceto","Cappella di S. Aniceto, Palazzo Altemps",I,None),
 (150,'1674',1674,'image',"Santa Maria in S. Ambrogio della Massima a Piazza Mattei","Rome, Sant'Ambrogio della Massima","Sant'Ambrogio della Massima",I,None),
 (150,'1675',1675,'image',"Santa Maria in S. Salvatore delle Cupelle","Rome, San Salvatore alle Coppelle","San Salvatore alle Coppelle",I,None),
 (150,'1676',1676,'image',"Santa Maria nelle Stanze di S. Ignazio al Gesù","Rome, Chiesa del Gesù (Stanze di Sant'Ignazio)","Stanze di S. Ignazio al Gesù",I,None),
 (150,None,1676,'image',"Santa Maria in Monterone","Rome, Santa Maria in Monterone","Santa Maria in Monterone",I,None),
 (150,None,1676,'image',"Santa Maria Porta Paradisi in S. Giacomo degli Incurabili","Rome, Santa Maria Porta Paradisi","Santa Maria Porta Paradisi (San Giacomo degli Incurabili)",I,None),
 (150,'1677',1677,'image',"Santa Maria della Pietà nell'Oratorio del P. Caravita","Rome, Oratorio del Caravita","Oratorio del P. Caravita",I,None),
 (150,None,1677,'image',"S. Maria in Trevi detta li Crociferi","Rome, Santa Maria in Trivio (Crociferi)","Santa Maria in Trivio",I,None),
 (150,None,1677,'image',"Santa Maria in S. Adriano in Campo Vaccino","Rome, Sant'Adriano al Foro","Sant'Adriano in Campo Vaccino",I,None),
 (150,'1678',1678,'image',"Santa Maria delle Grazie in S. Lorenzo in Lucina","Rome, San Lorenzo in Lucina (Madonna delle Grazie)","San Lorenzo in Lucina",I,None),
 (150,None,1678,'image',"Santa Maria della Purità in S. Andrea della Valle","Rome, Sant'Andrea della Valle","Sant'Andrea della Valle",I,None),
 (150,'1679',1679,'image',"Santa Maria nell'Oratorio vicino alla Scala Santa","Rome, Scala Santa","Oratorio presso la Scala Santa",I,None),
 (150,None,1679,'image',"Santa Maria in S. Vincenzo, ed Anastasio a Trevi","Rome, Santi Vincenzo e Anastasio a Trevi","SS. Vincenzo e Anastasio a Trevi",I,
   "A printer's ornament follows this entry; from 1681 the list includes images outside Rome."),
 (150,'1681',1681,'image',"Santa Maria in S. Biagio di Montepulciano","Montepulciano, San Biagio","San Biagio",I,None),
 (150,None,1681,'image',"Santa Maria di Provenzano","Siena (Provenzano)","Santa Maria di Provenzano",I,None),
 (150,'1682',1682,'image',"S. Maria di Ripatransone nel Piceno","Ripatransone",None,I,None),
 (151,None,1682,'image',"Santa Maria delle Grazie di Velletri","Velletri","Santa Maria delle Grazie",I,None),
 (151,None,1682,'image',"Santa Maria del Buonconsiglio di Genazano","Genazzano","Santa Maria del Buon Consiglio",I,None),
 (151,'1683',1683,'image',"Santa Maria del Soccorso di Genova","Genoa (Genova)","Santa Maria del Soccorso",I,None),
 (151,None,1683,'image',"Santa Maria al Mare diocesi di Fermo","Fermo (diocese)","Santa Maria a Mare",I,None),
 (151,'1684',1684,'image',"Santa Maria in Via di Camerino","Camerino","Santa Maria in Via",I,None),
 (151,None,1684,'image',"Santa Maria de Ruscelli fuori di Vallerano","Vallerano","Santa Maria del Ruscello",I,None),
 (151,None,1684,'image',"Santa Maria del Transito in S. Giovanni Laterano","Rome, San Giovanni in Laterano","San Giovanni in Laterano",I,None),
 (151,'1685',1685,'image',"Santa Maria di Mongiovino di Città della Pieve","Mongiovino (Panicale), diocese of Città della Pieve","Santuario di Mongiovino",I,None),
 (151,'1686',1686,'image',"Santa Maria nella Cattedrale di Forlì","Forlì","Cattedrale (Madonna del Fuoco)",I,None),
 (151,None,1686,'image',"Santa Maria nella Chiesa delle Monache dello Spirito Santo di Roma","Rome, Santo Spirito (nuns)","Chiesa delle Monache dello Spirito Santo",I,None),
 (151,'1687',1687,'image',"Santa Maria nella Chiesa di S. Marco de' Serviti di Pesaro","Pesaro","San Marco (Servites)",I,None),
 (151,None,1687,'image',"Santa Maria nel Monastero di Tor de' Specchi di Roma","Rome, Tor de' Specchi (monastery)","Monastero di Tor de' Specchi",I,None),
 (151,None,1687,'image',"Santa Maria nella Metropolitana di Urbino","Urbino","Cattedrale",I,None),
 (151,None,1687,'image',"Santa Maria in Santa Maria Nuova fuori di Cortona","Cortona","Santa Maria Nuova",I,None),
 (151,'1688',1688,'image',"Santa Maria nel Monastero delle Monache di Campo Marzo","Rome, Santa Maria in Campo Marzio (monastery)","Monastero delle Monache di Campo Marzio",I,None),
 (151,None,1688,'image',"Santa Maria di Grotta Ferrata","Grottaferrata","Abbazia di Grottaferrata",I,None),
 (151,'1689',1689,'image',"Santa Maria del Sasso nella Chiesa degli Agostiniani di Lucca","Lucca","Chiesa degli Agostiniani (Madonna del Sasso)",I,None),
 (152,'1690',1690,'image',"Santa Maria di Tirano in Valtelina diocesi di Como","Tirano (Valtellina)","Santuario della Madonna di Tirano",I,None),
 (152,None,1690,'image',"Santa Maria di Monte Nero vicino a Livorno","Montenero (Livorno)","Santuario di Montenero",I,None),
 (152,'1691',1691,'image',"Santa Maria Assunta nella Chiesa di Santa Maria presso S. Celso di Milano","Milan (Milano)","Santa Maria presso San Celso",I,None),
 (152,'1693',1693,'image',"Santa Maria della Colonella nella Chiesa de PP. del Terz'Ordine di S. Francesco fuori di Rimini","Rimini","Santa Maria della Colonnella (Franciscan Third Order)",I,None),
 (152,'1694',1694,'image',"Santa Maria in S. Pantaleo di Roma","Rome, San Pantaleo","San Pantaleo",I,None),
 (152,None,1694,'image',"Santa Maria della Neve di Frosinone","Frosinone","Santa Maria della Neve",I,None),
 (152,'1695',1695,'image',"Santa Maria de' Sette Dolori in San Marcello di Roma","Rome, San Marcello al Corso","San Marcello al Corso",I,None),
 (152,'1696',1696,'image',"S. Maria delle Vergini nella Chiesa de' Carmelitani di Macerata","Macerata","Chiesa dei Carmelitani (Santa Maria delle Vergini)",I,None),
 (152,None,1696,'image',"Santa Maria Lauretana nella Chiesa de Chierici Regolari di S. Paolo di Spoleto","Spoleto","Chiesa dei Barnabiti (Chierici Regolari di S. Paolo)",I,None),
 (152,None,1696,'image',"Santa Maria in S. Lorenzo in Borgo","Rome, San Lorenzo in Borgo (Scuole Pie)","San Lorenzo in Borgo",I,None),
 (152,'1703',1703,'image',"Santa Maria di Belvedere fuori di Città di Castello","Città di Castello","Santuario di Belvedere",I,
   "Briccolani has no entry for 1697-1702; Basilici-Bigliazzi note the gap and the omission of, e.g., Reggio Calabria 1722."),
 (152,None,1703,'image',"Santa Maria nella Chiesa del Nome di Maria in Roma","Rome, Santissimo Nome di Maria","Chiesa del Nome di Maria (S. Bernardo alla Colonna Traiana)",I,None),
 (152,'1704',1704,'image',"Santa Maria di Cibbona vicino alla Tolfa","Cibona (Tolfa)","Eremo di Cibona",I,None),
 (152,None,1704,'image',"Santa Maria del Presepe delle Monache di tutti i Santi di Siena","Siena","Monastero di Ognissanti (Madonna del Presepe)",I,None),
 (152,None,1704,'image',"Santa Maria d'Otranto nella Cattedrale d'Otranto","Otranto","Cattedrale",I,None),
 (153,None,1704,'image',"Santa Maria nella Cattedrale d'Orvieto","Orvieto","Cattedrale (Madonna di San Brizio)",I,None),
 (153,None,1704,'image',"Santa Maria di S. Giovanni di Val d'Arno","San Giovanni Valdarno","Santa Maria delle Grazie",I,None),
 (153,None,1704,'image',"Santa Maria del Lago vicino a Bertinoro in cura de Monaci Camaldolesi del Monastero d'Urano","Bertinoro","Santa Maria del Lago (Camaldolese of Urano)",I,None),
 (153,'1707',1707,'image',"Santa Maria della Cattedrale di Monte Pulciano","Montepulciano","Cattedrale (Madonna di San Martino)",I,None),
 (153,'1708',1708,'image',"Santa Maria nella Chiesa di S. Cristofaro della Penna de' Billi Diocesi di Monte Feltre","Pennabilli (Penna de' Billi)","San Cristoforo",I,None),
 (153,'1709',1709,'image',"Santa Maria della Giara nella Chiesa de' Teatini di Verona","Verona","Chiesa dei Teatini (Madonna della Ghiara)",I,None),
 (153,'1710',1710,'image',"Santa Maria Fonte de' Miracoli vicino a Caravaggio Diocesi di Cremona","Caravaggio","Santuario di Santa Maria del Fonte",I,None),
 (153,'1712',1712,'image',"Santa Maria di Monte Vergine nella Chiesa de' Benedettini della Provincia di Benevento","Montevergine (Monte Vergine, near Avellino)","Abbazia di Montevergine",I,None),
 (153,'1713',1713,'image',"Santa Maria della Pianta in Foligno","Foligno","Madonna del Pianto",I,"Printed 'della Pianta'; the image is the Madonna del Pianto (tomo IV dossier)."),
 (153,'1714',1714,'image',"Santa Maria del Capo Croce in Frascati","Frascati","Madonna di Capocroce",I,None),
 (153,None,1714,'image',"Santa Maria del Peratello vicino ad Imola","Imola","Santuario del Piratello",I,None),
 (153,'1715',1715,'image',"Santa Maria di Forano diocesi d'Osimo","Forano (Appignano), diocese of Osimo","Santa Maria di Forano",I,None),
 (153,None,1715,'image',"Santa Maria del Monte Tersatti diocesi di Segna in Dalmazia","Tersatto (Trsat), near Fiume (Rijeka)","Santuario di Tersatto",'Croatia',None),
 (153,None,1715,'image',"Santa Maria nella Chiesa della SSma Trinità di Viterbo","Viterbo","SS. Trinità (Madonna Liberatrice)",I,None),
 (154,'1716',1716,'image',"Santa Maria dell'Umiltà di Pistoja","Pistoia","Basilica della Madonna dell'Umiltà",I,None),
 (154,'1717',1717,'image',"Santa Maria in S. Pietro in Montorio di Roma","Rome, San Pietro in Montorio","San Pietro in Montorio",I,None),
 (154,None,1717,'image',"Santa Maria di Chiaromonte Czestochoviensi in Polonia","Częstochowa (Jasna Góra)","Jasna Góra",'Poland',None),
 (154,None,1717,'image',"Santa Maria delle Grazie vicino a Gorizia","Monte Santo (Sveta Gora), near Gorizia","Santa Maria delle Grazie (Monte Santo)",'Slovenia',None),
 (154,'1718',1718,'image',"Santa Maria del Soccorso di Monte Alcino","Montalcino","Madonna del Soccorso",I,None),
 (154,'1720',1720,'image',"Santa Maria della Misericordia d'Osimo","Osimo","Madonna della Misericordia",I,None),
 (154,'1721',1721,'image',"Santa Maria de Finibus Terrae nella diocesi d'Alessano","Santa Maria di Leuca (Finibus Terrae), diocese of Alessano","Santa Maria de Finibus Terrae",I,None),
 (154,None,1721,'image',"Santa Maria della Misericordia di Macerata","Macerata","Madonna della Misericordia",I,None),
 (154,'1723',1723,'image',"Santa Maria delle Grazie di Benevento","Benevento","Santa Maria delle Grazie",I,None),
 (154,None,1723,'image',"Santa Maria dell'Incoronata nell'Eremo de' Camaldolesi vicino a Benevento","Benevento, church of the Camaldolese","Eremo dei Camaldolesi (Madonna Incoronata)",I,None),
 (154,'1724',1724,'image',"Santa Maria nella Chiesa di S. Paolo Maggiore de' Teatini di Napoli","Napoli","San Paolo Maggiore (Theatines) — Madonna della Purità",I,None),
 (154,None,1724,'image',"Santa Maria de' Bisognosi sul Monte Cassoli diocesi di Marsi","Pereto / Rocca di Botte (Monte Carsoli), diocese of the Marsi","Santa Maria dei Bisognosi",I,"Printed 'Cassoli' for Carsoli."),
 (154,'1726',1726,'image',"Santa Maria di Galloro diocesi d'Albano","Galloro (Ariccia)","Santuario di Galloro",I,None),
 (154,None,1726,'image',"Santa Maria nella Chiesa di S. Fiorenzo di Perugia","Perugia","San Fiorenzo",I,None),
 (154,'1728',1728,'image',"Santa Maria del Suffraggio nella Collegiata di S. Giovan Batista delle Grotte, diocesi di Montefiascone","Grotte di Castro","Collegiata di S. Giovanni Battista (Madonna del Suffragio)",I,None),
 (155,'1729',1729,'image',"Santa Maria della Rotonda d'Albano","Albano","Santa Maria della Rotonda",I,None),
 (155,None,1729,'image',"Santa Maria degli Angeli nella Chiesa di S. Agata de Tessitori di Roma","Rome, Sant'Agata dei Tessitori","Sant'Agata dei Tessitori",I,None),
 (155,'1731',1731,'image',"Santa Maria del Glorioso di S. Severino","San Severino Marche","Santa Maria del Glorioso",I,None),
 (155,'1732',1732,'image',"Santa Maria Addolorata vicino a Jaroslavien","Jarosław","Madonna Addolorata",'Poland',None),
 (155,None,1732,'image',"Santa Maria Lauretana nella Chiesa di S. Abbondio de Teatini di Cremona","Cremona","Sant'Abbondio (Theatines) — Madonna Lauretana",I,None),
 (155,None,1732,'image',"Santa Maria nella Chiesa de Premostratensi di Moravia diocesi di Olmitz","Svatý Kopeček (Olomouc)","Premonstratensian church, diocese of Olomouc",'Czech Republic',None),
 (155,'1733',1733,'image',"Santissima Concezione nella Chiesa della Congregazione della V. Orsola Benincasa in Napoli","Napoli (Suor Orsola Benincasa)","Chiesa della Congregazione di Suor Orsola Benincasa",I,None),
 (155,'1734',1734,'image',"Santa Maria nella Chiesa de Carmelitani di Trapani in Sicilia","Trapani, Carmelite sanctuary of the Annunziata","Chiesa dei Carmelitani (Annunziata)",I,None),
 (155,None,1734,'image',"Santa Maria della Providenza nella Chiesa de' Teatini di Palermo","Palermo","Chiesa dei Teatini (Madonna della Provvidenza)",I,None),
 (155,'1736',1736,'image',"Santa Maria Annunziata nella Chiesa di S. Tommaso degli Agostiniani di Bruna in Moravia","Brno, St Thomas (Augustinians)","St Thomas (Augustinians)",'Czech Republic',None),
 (155,'1739',1739,'image',"Santa Maria in Monte, sopra Varese","Sacro Monte di Varese","Santa Maria del Monte",I,None),
 (155,'1740',1740,'image',"Santa Maria di Guadalupe vicino al Messico nell'Indie Occidentali","Mexicopolis (Mexico City)","Santuario di Guadalupe",'Mexico',
   "Listed by Briccolani as crowned in 1740. The Chapter conceded the crown (Boturini's petition, 1738) but the coronation was annulled by the Council of the Indies and never carried out (Balzamo 2023); the image was first crowned in 1895."),
 (156,'1741',1741,'image',"Santa Maria delle Grazie nella Chiesa de' Carmelitani di Monte Pulciano","Montepulciano","Chiesa dei Carmelitani (Madonna delle Grazie)",I,None),
 (156,None,1741,'image',"Santa Maria della Manna vicino a Cortona","Cortona (Manna)","Santa Maria della Manna",I,None),
 (156,'1742',1742,'image',"Santa Maria delle Grazie nella Chiesa degli Agostiniani di Aquapendente","Acquapendente","Chiesa degli Agostiniani (Madonna delle Grazie)",I,None),
 (156,None,1742,'image',"Santa Maria di Galliraccio Diocesi di Como","Gallivaggio (Valle Spluga), diocese of Como","Santuario di Gallivaggio",I,"Printed 'Galliraccio'."),
 (156,'1743',1743,'image',"Santa Maria de Avvocata nella Chiesa dell'Eremo de' Camandolesi nella Diocesi d'Amalfi","Maiori (Eremo dell'Avvocata), diocese of Amalfi","Eremo dei Camaldolesi (Madonna Avvocata)",I,None),
 (156,'1745',1745,'image',"Santa Maria Assunta nella Cattedrale d'Amelia","Amelia","Cattedrale",I,None),
 (156,None,1745,'image',"Santa Maria delle Grazie nella Chiesa de' Carmelitani di Jesi","Jesi","Chiesa dei Carmelitani (Madonna delle Grazie)",I,None),
 (156,'1747',1747,'image',"Santa Maria de' Lumi nella Chiesa de' Bernabiti di S. Severino","San Severino Marche","Chiesa dei Barnabiti (Madonna dei Lumi)",I,None),
 (156,None,1747,'image',"Santa Maria di Valle del Prato di Monticelli diocesi di Chiusi","Monticchiello (Pienza), diocese of Chiusi","Madonna di Valle Prata",I,None),
 (156,'1749',1749,'image',"Santa Maria della Pace di Giuliano Diocesi d'Aversa","Giugliano in Campania","Madonna della Pace",I,None),
 (156,None,1749,'image',"Santa Maria de Soviore di Monte Rosso diocesi di Genova","Monterosso al Mare","Santuario di Soviore",I,None),
 (156,None,1749,'image',"Santa Maria delle Vertighe di Monte Savino diocesi d'Arezzo","Monte San Savino","Santuario delle Vertighe",I,None),
 (156,'1750',1750,'image',"Santa Maria Libera Inferni nella Metropolitana di Palermo","Palermo","Cattedrale (Madonna Libera Inferni)",I,None),
 (157,'1751',1751,'image',"Santa Maria del Rosario nella Chiesa di S. Michel Arcangelo di Antegnate diocesi di Cremona","Antegnate","San Michele Arcangelo (Madonna del Rosario)",I,None),
 (157,'1752',1752,'image',"Santa Maria di S. Pietro del Piano Castrenaro diocesi di Suana","Castro (Piano di Castro), diocese of Sovana","San Pietro del Piano",I,None),
 (157,'1753',1753,'image',"Santa Maria de Custonacci di Monte S. Giuliano diocesi di Mazara","Custonaci","Santuario di Custonaci",I,None),
 (157,'1754',1754,'image',"S. Maria del Ponte vicino a Narni","Narni","Madonna del Ponte",I,None),
 (157,None,1754,'image',"S. Maria Annunziata in Benevento","Benevento","Annunziata",I,None),
 (157,'1759',1759,'image',"Santa Maria Mater Domini nella Chiesa de Monaci Basiliani di Nocera de' Pagani diocesi di Salerno","Nocera de' Pagani (Nocera Superiore), diocese of Salerno","Chiesa dei Basiliani (Materdomini)",I,None),
 (157,None,1759,'image',"Santa Maria di Macereto di Visso diocesi di Spoleti","Macereto (Visso)","Santuario di Macereto",I,None),
 (157,None,1759,'image',"S. Maria nella Catedrale di Verona","Verona (cathedral)","Cattedrale",I,None),
 (157,'1760',1760,'image',"Santa Maria nella Chiesa de' Cappucini vicino a Caephaludi","Cefalù","Chiesa dei Cappuccini",I,None),
 (157,'1761',1761,'image',"Santa Maria del Popolo nella Metropolitana di Montereale in Sicilia","Monreale","Cattedrale (Madonna del Popolo)",I,None),
 (157,'1763',1763,'image',"Santa Maria di Monte Allegro di Rapallo Diocesi di Genova","Rapallo","Santuario di Montallegro",I,None),
 (157,'1764',1764,'image',"Santa Maria dell'Olmo della Città della Cava","Cava de' Tirreni","Madonna dell'Olmo",I,None),
 (157,None,1764,'image',"Santa Maria in S. Pietro di Padova","Padua","San Pietro",I,None),
 (157,'1765',1765,'image',"Santa Maria della Prima primaria Congregazione nel Collegio Romano","Rome, Collegio Romano (Prima Primaria)","Congregazione Prima Primaria, Collegio Romano",I,None),
 (157,None,1765,'image',"Santa Maria in S. Rocco di Monte Rotondo","Monterotondo","San Rocco",I,None),
 (157,None,1765,'image',"Santa Maria di Quintigliolo nelle vicinanze di Tivoli","Tivoli (Quintiliolo)","Santuario di Quintiliolo",I,None),
 (158,None,1765,'image',"Santa Maria delle Grazie di Valle Valenza in Valtelina Diocesi di Como","Valle di Valenza (Valtellina), diocese of Como","Santa Maria delle Grazie",I,None),
 (158,'1766',1766,'image',"Santa Maria di Costantinopoli d'Avellino","Avellino","Santa Maria di Costantinopoli",I,None),
 (158,'1767',1767,'image',"Santa Maria dell'Orto di Chiaveri Diocesi di Genova","Chiavari (Clavarium), Liguria","Santuario di Nostra Signora dell'Orto",I,None),
 (158,'1768',1768,'image',"Santa Maria del Mare in Maggiore Diocesi d'Amalfi","Maiori","Santa Maria a Mare",I,None),
 (158,'1769',1769,'image',"Santa Maria della Rosa Diocesi di Genova","Genoa (diocese)","Santa Maria della Rosa",I,None),
 (158,None,1769,'image',"Santa Maria di Monopoli nel Regno di Napoli","Monopoli (Apulia)","Madonna della Madia",I,None),
 (158,'1770',1770,'image',"Santa Maria della Misericordia di Savona","Savona","Santuario della Misericordia",I,None),
 (158,None,1770,'image',"Santa Maria del Porto Salvo di Napoli","Napoli (Portosalvo)","Santa Maria di Portosalvo",I,None),
 (158,'1771',1771,'image',"Santa Maria Assunta del Castello del Piano Diocesi di Chiusi","Castel del Piano, diocese of Chiusi","Santa Maria Assunta",I,None),
 (158,None,1771,'image',"Santa Maria di Costantinopoli di Bari","Bari","Santa Maria di Costantinopoli",I,None),
 (158,'1772',1772,'image',"Santa Maria del Principio nella Chiesa di Santa Restituta di Napoli","Napoli (Santa Restituta)","Santa Restituta (Madonna del Principio)",I,None),
 (158,None,1772,'image',"Santa Maria del Soccorso di Vezzano Diocesi di Sarzana","Vezzano Ligure","Madonna del Soccorso",I,None),
 (158,None,1772,'image',"Santa Maria di Moncheri Diocesi d'Alba","Monchiero","Santa Maria",I,None),
 (158,'1773',1773,'image',"Santa Maria del Rosario nella Chiesa della Santissima Trinità del Piano Diocesi di Sorrento","Piano di Sorrento","SS. Trinità (Madonna del Rosario)",I,None),
 (159,None,1773,'image',"Santa Maria della Natività Pozcaioviens, Luceorien diaecesis in Polonia","Poczajów (Pochaiv)","Poczajów (diocese of Łuck)",'Ukraine',None),
 (159,'1774',1774,'image',"Santa Maria nella Catedrale di Groseto","Grosseto","Cattedrale (Madonna delle Grazie)",I,None),
 (159,'1775',1775,'image',"Santa Maria de' Miracoli nella Chiesa delle Monache della Providenza in Napoli","Napoli (Monache della Provvidenza)","Chiesa delle Monache della Provvidenza (Madonna dei Miracoli)",I,None),
 (159,'1777',1777,'image',"Santa Maria di Civita nella Chiesa d'Itri diocesi di Gaeta","Itri","Santuario della Madonna della Civita",I,None),
 (159,'1778',1778,'image',"Santa Maria della Concezione nella Cattedrale d'Aquapendente","Acquapendente (cathedral)","Cattedrale (Madonna della Concezione)",I,None),
 (159,None,1778,'image',"Santa Maria del Soccorso di Cori","Cori","Madonna del Soccorso",I,None),
 (159,None,1778,'image',"Santa Maria della Misericordia di Fabriano","Fabriano","Madonna della Misericordia",I,None),
 (159,None,1778,'image',"Santa Maria nella Chiesa de Capucini di Palermo","Palermo (Cappuccini)","Chiesa dei Cappuccini",I,None),
 (159,None,1778,'image',"Santa Maria di Col de' Venti della Muccia diocesi di Camerino","Muccia (Col di Venti)","Madonna di Col di Venti",I,None),
 (159,None,1778,'image',"Santa Maria di Marzano diocesi di Nola","Marzano (diocese of Nola)","Santa Maria di Marzano",I,None),
 (159,None,1778,'image',"Santa Maria delle Grazie vicino a Calatafimi Diocesi di Mazzara","Calatafimi","Santa Maria delle Grazie",I,None),
 (159,None,1778,'image',"Santa Maria delle Grazie nella Metropolitana di Ferrara","Ferrara","Cattedrale (Madonna delle Grazie)",I,None),
 (159,None,1778,'image',"Santa Maria di Costantinopoli nella Chiesa di Granani Diocesi di Lettere","Gragnano, diocese of Lettere","Santa Maria di Costantinopoli",I,"Printed 'Granani'."),
 (159,None,1778,'image',"Santa Maria delle Grazie vicino a Ponticelli in Sabina Noviziato de Riformati del Ritiro di S. Bonaventura","Ponticelli (Sabina)","Ritiro di S. Bonaventura (Riformati) — Madonna delle Grazie",I,None),
 (160,'1779',1779,'image',"Santa Maria della Potenza nella Chiesa di S. Giorgio maggiore di Napoli","Napoli (San Giorgio Maggiore)","San Giorgio Maggiore (Madonna della Potenza)",I,None),
 (160,'1780',1780,'image',"Santa Maria nella Chiesa de Cappucini di Casal Posterlengo diocesi di Lodi","Casalpusterlengo","Chiesa dei Cappuccini",I,None),
 (160,None,1780,'image',"Santa Maria di Costantinopoli nella Chiesa di S. Eustachio della Città d'Aquaviva nel Regno di Napoli","Acquaviva delle Fonti","Sant'Eustachio (Santa Maria di Costantinopoli)",I,None),
 (160,'1781',1781,'image',"Santa Maria dei Sette Veli nella Chiesa Collegiata di Foggia Diocesi di Troja","Foggia","Collegiata (Madonna dei Sette Veli)",I,None),
 (160,'1782',1782,'image',"Santa Maria di tutte le Grazie della Quercia nella Chiesa di Conflenti Inferiori Diocesi di Marturano","Conflenti","Madonna della Quercia (di Visora)",I,None),
 (160,None,1782,'image',"Santa Maria de' Miracoli nella Chiesa d'Alcami Diocesi di Mazzara in Sicilia","Alcamo","Madonna dei Miracoli",I,None),
 (160,'1783',1783,'image',"Santa Maria nella Chiesa di S. Vito di Positano Diocesi d'Amalfi","Positano","San Vito",I,None),
 (160,'1784',1784,'image',"Santa Maria della Misericordia nella Chiesa di S. Pietro di Jesi","Jesi (San Pietro)","San Pietro (Madonna della Misericordia)",I,None),
 (160,None,1784,'image',"Santa Maria del Presepio nell'Oratorio de' Minori Riformati vicino a Palermo","Palermo (Minori Riformati)","Oratorio dei Minori Riformati (Madonna del Presepio)",I,None),
 (160,'1785',1785,'image',"Santa Maria Lauretana nella Chiesa de' Cappucini della Città Vittoria Diocesi di Siracusa","Vittoria (Sicily)","Chiesa dei Cappuccini (Madonna Lauretana)",I,None),
 (161,None,1785,'image',"Santa Maria del Carmine di Nocera de' Pagani","Nocera de' Pagani (Nocera Inferiore)","Madonna del Carmine",I,None),
 (161,'1786',1786,'image',"Santa Maria delle Grazie nella Chiesa de' Domenicani di Val di Novi Diocesi di Capaccio","Vallo della Lucania (Novi Velia), diocese of Capaccio","Chiesa dei Domenicani (Madonna delle Grazie)",I,None),
 (161,None,1786,'image',"Santa Maria delle Grazie alla Pietra del Pesce in Napoli","Napoli (Pietra del Pesce)","Santa Maria delle Grazie a Pietra del Pesce",I,None),
 (161,None,1786,'image',"Santa Maria Lauretana di Forigi Diocesi d'Ischia","Forio (Ischia)","Santa Maria di Loreto",I,None),
 (161,'1688',1788,'image',"Santa Maria della Natività di Valperga","Valperga","Santa Maria della Natività",I,"Printed '1688', a misprint for 1788 (the entry stands between 1786 and 1790)."),
 (161,'1790',1790,'image',"Santa Maria della Neve vicino a Palombara Ritiro de Minori Osservanti","Palombara Sabina","Ritiro dei Minori Osservanti (Madonna della Neve)",I,None),
 (161,'1791',1791,'image',"Santa Maria di Costantinopoli d'Ischia","Ischia","Santa Maria di Costantinopoli",I,None),
 (161,None,1793,'image',"Santa Maria nella Chiesa Parrochiale di S. Benedetto in Piscinula Coronata alli 15. Settembre 1793. da S. A. R. l'Eminentissimo Cardinal denominato Duca di Yorch Vice Cancelliere di Santa Chiesa, e Arciprete della Basilica","Rome, San Benedetto in Piscinula","San Benedetto in Piscinula",I,
   "Added after the dated series, with a full date (15 September 1793) and the crowning prelate (Cardinal Henry Benedict Stuart, Duke of York, Archpriest of the Basilica). Briccolani's footnote (1): 'L'Istoria delle Imagini Coronate in Roma dal Reverendissimo Capitolo di S. Pietro, in quattro tomi in 8. L'anno 1795 presso il Salomoni fù stampata' — i.e. Bombelli's Raccolta (actually 1792)."),
]

import re
TRAIL=re.compile(r"\s+(?:[Dd]iocesi\s+d[i'’]|nel Regno di|nel Piceno|in Sicilia|in Polonia|in Dalmazia|in Moravia|in Valtelina|"
                 r"nell'Indie|vicino a|vicino al|vicino ad|fuori di|fuori delle|presso|sopra|di Roma|in Roma|"
                 r"della Provincia|Coronata alli)\b.*$")
def short(text):
    """The title without the trailing place phrase: 'Santa Maria del Mare in Maggiore Diocesi d'Amalfi'
    -> 'Santa Maria del Mare in Maggiore'. The place is carried by `locality`."""
    return re.sub(r"\s+(?:nella|nel|nell'|in|di|de|d')$","",TRAIL.sub('',text).rstrip(' ,.'))
rows=[]
for n,(pg,yp,y,kind,text,loc,church,country,notes) in enumerate(ROWS,1):
    rows.append({'no':n,'page':pg,'year_printed':yp,'year':y,'kind':kind,'text_as_printed':text,'title':short(text),
                 'locality':loc,'church_or_place':church,'country':country,'notes':notes,'parent_no':None})
# a Child's crown belongs to the image listed under the same church earlier in the series
for r in rows:
    if r['kind']=='child':
        par=[x for x in rows if x['kind']=='image' and x['no']<r['no'] and x['locality']==r['locality']]
        assert par, r['text_as_printed']
        r['parent_no']=par[-1]['no']
out={'source':("Vincenzo Briccolani, Descrizione della sacrosanta Basilica Vaticana, sue piazze, portici, grotte, sacristie, "
  "parti superiori, interne, ed esterne e loro misure. Con l'Elenco delle Consagrazioni degli Altari, Catalogo delle "
  "Reliquie, e Serie delle Coronazioni delle Immagini di Maria Vergine fatte dal reverendissimo Capitolo Vaticano. "
  "Edizione seconda, Roma, Salomoni, 1800, pp. 144-161: 'Serie delle Sagre Immagini di Maria Vergine coronate con la "
  "Corona d'Oro dal Rmo Capitolo di S. Pietro in Vaticano, secondo il Pio Legato del Conte Alessandro Sforza Piacentino'."),
 'scan':'https://archive.org/details/gri_33125011212400 (Getty Research Institute copy; PDF pp. 158-175); also HathiTrust ucm.5322468201',
 'transcribed':'2026-09-14, page by page against the scan',
 'note':("The earliest printed register of the Chapter's coronations. Year by year, 1631-1791 (+1793), Rome only until 1679, "
  "then Italy and abroad. Years only; no day, month or archival reference. `year_printed` is the year as it stands in the "
  "margin (null where an entry continues the year above); `year` is the year the entry belongs to. `title` is the entry without its trailing place phrase. `kind` = 'child' marks "
  "the twelve separate crowns for the Bambino Gesù of an image already crowned. `locality` is a modern form chosen to "
  "match the catalogue; `text_as_printed` is Briccolani's own wording."),
 'row_count':len(rows),'rows':rows}
json.dump(out,open(REPO/'data/briccolani-1800-serie.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
import collections
print('rows',len(rows),'child crowns',sum(1 for r in rows if r['kind']=='child'),
      'Rome',sum(1 for r in rows if r['locality'].startswith('Rome')),
      'years',min(r['year'] for r in rows),'-',max(r['year'] for r in rows))
print(collections.Counter(r['country'] for r in rows))
