"""Bombelli (1792), *Raccolta delle immagini della Beatissima Vergine ornate della corona d'oro* — transcription.

[Pietro Bombelli, incisore], *Raccolta delle immagini della Beatissima Vergine ornate della corona
d'oro dal R.mo Capitolo di S. Pietro, con una breve ed esatta notizia di ciascuna immagine*, 4 tomi
in 8°, Roma, Salomoni, 1792 (the plates of tomo IV are dated Roma 1793). One notice of four to ten
pages per image, facing an engraving by Bombelli whose caption gives the title, the support and size
of the original ("in Tavola, Alta Pal. 4, Lar. 3") and the year of the crowning. The notices draw on
"le memorie dell'archivio della Basilica Vaticana", the *memoriali* and the *atti capitolari*, and
give what no printed register gives: the DAY of the crowning, often the day of the decree, the
canons deputed, the cost of the crowns, and the separate crown for the Child.

Tomi II–IV are on the Internet Archive from the Google scans of the Biblioteca Nazionale Centrale di
Roma (bub_gb_JhP2LAUmGjUC = II, bub_gb_rHbfIRvNjxkC = III, bub_gb_9vADu01fhEAC = IV); tomo I has
not been found online. Transcribed on 14 September 2026 from the OCR text checked against the page
images wherever a date or a number was in doubt, and the caption of every plate read from the scan.
Bombelli's total is "cenquattro miracolose Imagini coronate": the 74 here in tomi II–IV, the other
thirty in tomo I. The sixteen images of the *Appendice* in tomo IV are, in his own words, "sebben non
sieno coronate", and are not transcribed.

Output: data/bombelli-1792-raccolta.json
"""
import json,pathlib,re
REPO=pathlib.Path(__file__).resolve().parent.parent
R='Rome'
def row(tomo,page,heading,caption,title,church,locality,date=None,decree=None,child=None,cost=None,deputies=None,
        medium=None,size=None,caption_year=None,text=None,notes=None):
    return dict(tomo=tomo,page=page,heading_as_printed=heading,caption_as_engraved=caption,title=title,
                church_or_place=church,locality=locality,coronation_date=date,concession_date=decree,child_date=child,
                crown_cost_scudi=cost,deputies=deputies,medium=medium,size_palmi=size,caption_year=caption_year,
                text_as_printed=text,notes=notes)
ROWS=[
# ---------------------------------------------------------------- Tomo II (30 notices)
row('II',1,"La Madonna del Soccorso in S. Pietro in Vaticano","La Madonna del Soccorso nella Cappella Gregoriana in S. Pietro in Vaticano",
    "Madonna del Soccorso","Basilica Vaticana, Cappella Gregoriana","Rome, Vatican Basilica (Cappella Gregoriana)",
    date='1643-11-17',child='1647',medium='muro',size='3 x 2',caption_year=1643,
    text="il Capitolo Vaticano coronò la Divina Madre a' 17. Novembre 1643., e quattro anni dappoi il divin Figliuolo",
    notes="Placed in the Cappella Gregoriana by Gregory XIII on 12 February 1578."),
row('II',7,"La Madonna del Transito, e del Riposo in S. Giovanni in Laterano","Transito della Madonna in S. Gio. Laterano",
    "Madonna del Transito o del Riposo","Basilica di S. Giovanni in Laterano","Rome, San Giovanni in Laterano",
    date='1684-08-10',decree='1683-12',cost='97.85',deputies="Canonici Angelo Paracciani e Giuseppe Baldo (Vaticano); Bottini e Casali (Lateranense)",
    medium='muro',size='4 x 7',caption_year=1684,
    text="nel Decembre del 1683. formarono il decreto, che si eseguì a' 10. Agosto del 1684., impiegandovi la somma di Scudi 97. 85."),
row('II',13,"Madonna del Fonte presso la Basilica di S. Giovanni","La Madonna del Fonte in S. Gio. Laterano",
    "Madonna del Fonte","S. Giovanni in Fonte (battistero lateranense)","Rome, San Giovanni in Fonte (Lateran baptistery)",
    date='1647',medium='muro',size='3 x 2',caption_year=1647,
    text="Nel 1647. seguì con giubilo comune la coronazione della divina Madre, e del S. Bambino.",
    notes="Mother and Child crowned together."),
row('II',21,"Madonna nell'Oratorio del SS.mo Sagramento contiguo alla Scala Santa","La Madonna nel Oratorio alla Scala Santa",
    "Madonna","Oratorio del SS. Sacramento alla Scala Santa","Rome, Scala Santa",
    date='1679-07-08',cost='190',deputies="Canonici Lodovico Palagi e Giulio Ricci",medium='tavola',size='3 x 2',caption_year=1679,
    text="furono decretate le corone del prezzo di Scudi 190. Lodovico Palagi, e Giulio Ricci Canonici della Vaticana recarono il dono, ed alla loro presenza seguì la coronazione agli 8. Luglio 1679.",
    notes="Crowns for Mother and Child. Balzamo 2023 gives the same day."),
row('II',29,"Madonna della Clemenza nella Basilica di S. Maria in Trastevere","La Madonna della Clemenza in S. Maria in Trastevere",
    "Madonna della Clemenza","Basilica di S. Maria in Trastevere","Rome, Santa Maria in Trastevere (Madonna della Clemenza)",
    date='1659-11-02',medium='tavola',size='10 x 7',caption_year=1659,
    text="La solenne coronazione decretata dal Rmo Capitolo di S. Pietro seguì il dì 2. novembre del 1659."),
row('II',39,"Madonna di Strada Cupa venerata nella Basilica di S. Maria in Trastevere","La Madonna di Strada Cupa in S. Maria in Trastevere",
    "Madonna di Strada Cupa","Basilica di S. Maria in Trastevere (cappella Cecchini / d'Aste)","Rome, Santa Maria in Trastevere",
    date='1634-04-05',medium='muro',size='4 x 3',caption_year=1634,
    text="questa miracolosa Immagine coronata con quella del Bambino il dì 5. aprile 1634.",
    notes="Mother and Child crowned together; the image was found in 1624 and carried to the basilica on 27 June 1624."),
row('II',49,"Madonna nella Chiesa di S. Aniceto Papa e Martire nel Palazzo del Duca Altemps","La Madonna nella Chiesa di S. Aniceto nel Palazzo Altemps",
    "Madonna","S. Aniceto nel Palazzo Altemps","Rome, Palazzo Altemps, chapel of Sant'Aniceto",
    date='1673-04-15',medium='tavola',size='5 x 4',caption_year=1673,
    text="il dì 15. Aprile 1673 i Canonici deputati recarono le corone per Gesù, e Maria al Sig. Duca Pietro Altemps ... il sagro rito, che si eseguì alla presenza de' Canonici stessi",
    notes="Printed '2673' and corrected to 1673 in the errata. Balzamo 2023 gives 12 April 1673; Bombelli, citing the 'Atti capitol.', the 15th."),
row('II',53,"La Madonna del Popolo","La Madonna del Popolo","Madonna del Popolo","S. Maria del Popolo","Rome, Santa Maria del Popolo",
    date='1634',child='1667-09-06',cost='151 (Mother); 67.39 (Child)',medium='tavola',size='5 x 3',caption_year=1634,
    text="ebbe la sorte di offerir la corona d'oro del valore di sc. 151. quel suo diletto Divoto il Conte Sforza nel 1634. ... Lasciò al venerando Capitolo vaticano l'onore di coronare il S. Bambino con corona pur d'oro del valore di scudi 67. 39. il dì 6. settembre 1667.",
    notes="Crowned by Count Sforza himself in 1634; the Child by the Chapter on 6 September 1667."),
row('II',61,"La Madonna detta Porta Paradisi","S. Maria Porta Paradisi unita al Ospedale di S. Giacomo delli Incurabili",
    "Madonna","S. Maria Porta Paradisi (Ospedale di S. Giacomo degli Incurabili)","Rome, Santa Maria Porta Paradisi",
    date='1676-07-29',medium='tavola',size='3 x 2',caption_year=1676,
    text="decretarono le corone a Gesù, e a Maria. Seguì la coronazione a' 29 luglio 1676."),
row('II',65,"Madonna nella Chiesa volgarmente detta Tempio del Sole","S. Maria del Sole incontro la Bocca della Verità",
    "Madonna del Sole","S. Maria del Sole, incontro la Bocca della Verità (Tempio di Vesta)","Rome, Santa Maria del Sole",
    date='1669-05-18',medium='muro',size='3½ x 2½',caption_year=1665,
    text="il Rndo Capitolo a' 18. di maggio 1669. diè le due corone per Maria, e Gesù a D. Giuseppe Papini deputato del Card. ...",
    notes="The notice says 18 May 1669; the plate says 1665, as does Briccolani. Left as the notice gives it."),
row('II',69,"Madonna di S. Pier Montorio","La Madonna della Lettera in S. Pietro in Montorio",
    "Madonna della Lettera","S. Pietro in Montorio","Rome, San Pietro in Montorio",
    date='1717-05-02',decree='1716',medium='muro',size='10 x 7',caption_year=1717,
    text="fecero istanza per la corona a' 9. Agosto 1716. Furon dal Capitolo vaticano accordate le corone a Maria, ed al S. Bambino; ma la coronazione si differì a 2. Maggio 1717. per celebrarla con sontuosità di apparato",
    notes="The wall painting was cut from its wall and carried to the church on 9 August 1714."),
row('II',75,"Madonna d'Araceli","La Madonna del Araceli","Madonna d'Araceli","S. Maria in Aracoeli","Rome, Santa Maria in Aracoeli",
    date='1636',cost='150',medium='tavola',size='5 x 4',caption_year=1636,
    text="Questa veneranda effigie fu coronata vivendo il Conte Alessandro Sforza nel 1636., e s'impiegaron per la corona scudi 150."),
row('II',79,"Madonna di S. Gregorio a Monte Celio","La Madonna di S. Gregorio nella Cappella Salviati a Monte Celio",
    "Madonna","S. Gregorio al Celio, Cappella Salviati","Rome, San Gregorio al Celio (Cappella Salviati)",
    date='1658-09-14',decree='1656',medium='muro',size='4 x 3',caption_year=1658,
    text="Il dì 14 settembre del 1658. ebber que' Religiosi la richiesta corona, e nel dì medesimo fu coronata la rispettabile Immagine",
    notes="Petition of the Camaldolese in 1656."),
row('II',85,"Madonna di S. Giovannino a Campo Marzo","La Madonna di S. Giovannino vicino le Monache di S. Silvestro in Capite",
    "Madonna","S. Giovannino in Campo Marzio (Mercedari)","Rome, San Giovannino in Campo Marzio (Mercedarians)",
    date='1650-06-03',decree='1649',medium='muro',size='5 x 4',caption_year=1650,
    text="Chieserla que' Religiosi nel 1649., e ai 3. di giugno 1650. appagati della richiesta la coronarono con divota solennità."),
row('II',91,"Madonna nella Chiesa delle Monache di S. Anna a' Funari","La Madonna nella Chiesa delle Monache di S. Anna",
    "Madonna","S. Anna dei Funari (Falegnami), monache benedettine","Rome, Sant'Anna dei Falegnami",
    date='1652',decree='1651-12-13',medium='muro',size='3 x 3',caption_year=1652,
    text="fu accordata la corona sotto il dì 13 decembre 1651., seguitone l'atto nel 1652."),
row('II',97,"La Madonna nella Chiesa di S. Gio. Calibita all'Isola detta de' Benfratelli","La Madonna nella Chiesa de' Benfratelli",
    "Madonna","S. Giovanni Calibita (Fatebenefratelli)","Rome, San Giovanni Calibita",
    date='1664-03-19',decree='1664-01-14',medium='muro',size='5 x 4',caption_year=1664,
    text="fu decretata la Corona a' 14. Gennaro 1664., ed eseguita la coronazione a' 19. Marzo dell'anno stesso."),
row('II',101,"La Madonna di Loreto nell'Archiconfraternita de' Marchegiani","La Madonna di Loreto in S. Salvatore in Lauro",
    "Madonna di Loreto","S. Salvatore in Lauro (Arciconfraternita dei Marchigiani)","Rome, San Salvatore in Lauro",
    date='1644',child='1646',medium='legno',size='5½',caption_year=1644,
    text="fu coronata dal Capitolo vaticano nel 1644. e due anni accanto fu offerta ancor la corona al S. Bambino.",
    notes="Then in S. Michele a Ripetta; the confraternity acquired S. Salvatore in Lauro on 5 April 1656."),
row('II',105,"Madonna delle Grazie in S. Salvatore in Lauro","La Madonna delle Grazie in S. Salvatore in Lauro",
    "Madonna delle Grazie","S. Salvatore in Lauro","Rome, San Salvatore in Lauro",
    date='1654',medium='tela',size='6 x 4',caption_year=1654,
    text="si ottenne la corona dal reverendo Capitolo Vaticano l'anno 1654."),
row('II',111,"Madonna di Loreto a Colonna Trajana","La Madonna di Loreto de Fornari",
    "Madonna di Loreto","S. Maria di Loreto dei Fornari (Colonna Traiana)","Rome, Santa Maria di Loreto (Colonna Traiana)",
    date='1660',medium='tavola',size='7 x 4',caption_year=1660,
    text="la corona d'oro offertale dal Capitolo vaticano per istanza dell'Università nel 1760.",
    notes="The notice prints '1760', a misprint: the plate says 1660, as does Briccolani, and the notice itself sets the crown among seventeenth-century events. Petition of the Università dei Fornari."),
row('II',117,"Madonna delle Grazie a Porta Angelica","La Madonna delle Grazie a Porta Angelica",
    "Madonna delle Grazie","S. Maria delle Grazie a Porta Angelica","Rome, Santa Maria delle Grazie a Porta Angelica",
    date='1644-06-09',cost='65',medium='tavola',size='1 x 0.7',caption_year=1644,
    text="indussero il Capitolo vaticano alla coronazione, che seguì a 9. giugno 1644. coll'impiego di sc. 65."),
row('II',123,"Madonna nella Chiesa della SS. Trinità de' Pellegrini","La Madonna nella Chiesa della SS.ma Trinità de Pellegrini",
    "Madonna","SS. Trinità dei Pellegrini","Rome, Santissima Trinità dei Pellegrini",
    date='1654-06-21',medium='muro',size='3 x 2',caption_year=1654,
    text="Il Capitolo Vaticano le destinò la Corona, di cui fu fregiata a' 21. Giugno 1654."),
row('II',129,"Madonna in Campo Marzo","La Madonna nella Chiesa delle Monache di Campo Marzo",
    "Madonna","S. Maria della Concezione in Campo Marzio (monache benedettine), chiesa","Rome, Santa Maria in Campo Marzio (nuns)",
    date='1655',medium='tavola',size='4 x 3',caption_year=1655,text=None,
    notes="The notice tells the image's history (the fire, the well, Michelangelo's frame) but gives no date for the crowning; the year is the plate's."),
row('II',135,"Madonna nella Chiesa interiore del Monistero di Campo Marzo","La Madonna dentro il Monastero delle Monache di Campo Marzo",
    "Madonna","S. Maria in Campo Marzio, chiesa interiore del monastero","Rome, Santa Maria in Campo Marzio (monastery)",
    date='1688-09-12',decree='1688',cost='76',deputies="Canonici Mattei e Ricci (esaminatori)",medium='tavola',size='4 x 2',caption_year=1688,
    text="porser supplica nel 1688. al Rmo Capitolo per la Corona. I Canonici Mattei, e Ricci furon gli Esaminatori ... spedirono il decreto, e a' 12. settembre dell'anno stesso, con pubblico strumento fecero all'Abadessa, ed alle Monache la consegnazione della Corona, per la quale s'impiegò la somma di sc. 76.",
    notes="The nuns' memoriale is 'nell'archivio del capitolo vaticano'."),
row('II',139,"Madonna di S. Martino a' Monti","La Madonna in S. Martino a Monti","Madonna","S. Martino ai Monti","Rome, San Martino ai Monti",
    date='1659',cost='140',medium='tela',size='5 x 4',caption_year=1659,
    text="la corona che accordarono meritamente alla divina Madre, e al S. Bambino, impiegandovi la somma Sc. 140. Cadde la coronazione l'anno 1659."),
row('II',145,"Madonna in S. Prassede","La Madonna in S.ta Prassede detta Orto Paradisi","Madonna","S. Prassede (detta Orto Paradisi)","Rome, Santa Prassede",
    date='1655',medium='musaico',size='5 x 4',caption_year=1665,
    text="Il merito dell'Immagine mosse ancora il venerabile Capitolo vaticano a coronarla, siccome fece l'anno 1655.",
    notes="The plate reads 1665; the notice says 1655, as does Briccolani. A Polish bishop had left two gold crowns to the image in 1650."),
row('II',151,"Madonna della Misericordia nella Chiesa delle Monache dello Spirito Santo","La Madonna delle Monache dello Spirito Santo",
    "Madonna della Misericordia","Monache dello Spirito Santo","Rome, Santo Spirito (nuns)",
    date='1686-11-28',decree='1686',medium='muro',size='6 x 5',caption_year=1686,
    text="Monsig. Albani, poi Papa Clemente XI. ... si fece postulatore della corona, e ne fece istanza nel predetto anno 1686. Il Rmo Capitolo vi condiscese, e la coronazione seguì a' 28. novembre dell'anno accennato.",
    notes="The relazione, before the notary Anton Cimarroni on 15 June 1686, 'si conserva nell'archivio capitolar di S. Pietro'."),
row('II',159,"Madonna che si venera dentro il Monistero di S. Marta","La Madonna nel Monastero di S.ta Marta",
    "Madonna","Monastero di S. Marta al Collegio Romano","Rome, Santa Marta al Collegio Romano",
    date='1645-11-20',child='1646-09-01',medium='muro',size='6 x 4',caption_year=1646,
    text="il Ven. Capitolo per mezzo de' due Canonici deputati incoronò la divina Signora a' 20. novembre del 1645. Fecero le Religiose nuova istanza per la corona al Santo Bambino, e nell'anno seguente al primo dì di settembre furono compiaciute",
    notes="The plate reads 1646, the year of the Child's crown."),
row('II',165,"Madonna della Pace","La Madonna della Pace","Madonna della Pace","S. Maria della Pace","Rome, Santa Maria della Pace",
    date='1634-07-29',cost='152',medium='muro',size='5 x 4',caption_year=1634,
    text="La Corona le fu offerta dal medesimo Istitutore il Conte Sforza a' 29. Luglio 1634., ed importò Scudi 152.",
    notes="Crowned by Count Sforza himself."),
row('II',171,"Madonna nella Chiesa del Nome di Maria a Colonna Trajana","La Madonna nella Chiesa del SS.mo Nome di Maria",
    "Madonna","SS. Nome di Maria al Foro Traiano","Rome, Santissimo Nome di Maria",
    date='1703',medium='tavola',size='4 x 3',caption_year=1703,
    text="il venerando Capitolo di S. Pietro coronò la divina madre, e 'l S. Bambino nel 1703.",
    notes="Bombelli writes in 'il corrente 1792'."),
row('II',185,"Madonna della Vittoria","La Madonna della Vittoria","Madonna della Vittoria","S. Maria della Vittoria","Rome, Santa Maria della Vittoria",
    date='1635-07-06',cost='144',medium='tavola',size='1½ x 1',caption_year=1633,
    text="La solenne coronazione di questa Santa Imagine seguì a' 6. Luglio 1635. vivendo il Conte Alessandro Sforza, il quale impiegò nella corona 144. scudi.",
    notes="The notice says 6 July 1635; the plate says 1633, as does Briccolani. Crowned by Count Sforza himself."),
# ---------------------------------------------------------------- Tomo III (30 notices)
row('III',1,"La Madonna della Colonna nella Basilica Vaticana","La Madonna della Colonna in S. Pietro in Vatic.",
    "Madonna della Colonna","Basilica Vaticana","Rome, Vatican Basilica (Madonna della Colonna)",
    date='1645-02-07',child='1645-10-11',medium='marmo',size='4 x 3',caption_year=1645,
    text="Il Reverendo Capitolo ornò di corona la divina Madre a' 7. febrajo 1645, e agli 11. ottobre dell'anno stesso il divin Figliuolo.",
    notes="Zander/Magister 2011 give 1 January 1645. Translated to its altar on 2 February 1607 (Grimaldi, Istromenti delle Traslazioni, fol. 98)."),
row('III',5,"Immagine di Maria sotto il titolo della SS.ma Concezione nella insigne Collegiata di S. Lorenzo in Damaso","SS.ma Concezione in S. Lorenzo e Damaso",
    "SS. Concezione","S. Lorenzo in Damaso","Rome, San Lorenzo in Damaso",
    date='1635',medium='tavola',size='4 x 3',caption_year=1635,
    text="La coronazione seguì nel predetto anno 1635., vivendo ancora il pio istitutore delle corone il Conte Sforza.",
    notes="Moved to its chapel by Pietro da Cortona on 20 August 1635."),
row('III',11,"La Madonna della Traspontina","S. Maria in Traspontina","Madonna","S. Maria in Traspontina","Rome, Santa Maria in Traspontina",
    date='1641-06-15',child='1651-04',cost='104.50 (Mother); 34 (Child)',medium='tavola',size='3 x 2',caption_year=1651,
    text="Dalle memorie dell'archivio della Basilica Vaticana rilevo che l'anno 1641. il P. Teodoro Straccio Maestro Generale de' Carmelitani fece istanza per la corona ... a 15. giugno 1641. seguì l'offerta della corona valutata Sc. 104. 50. Successivamente nell'aprile del 1651. il S. Bambino fu fregiato della medesima del valore di scudi 34.",
    notes="The plate reads 1651, the year of the Child's crown. The memoriale 'si conserva nell'archivio del Capitolo'."),
row('III',15,"La Madonna della Scala","La Madonna della Scala in Trastevere","Madonna della Scala","S. Maria della Scala","Rome, Santa Maria della Scala (Trastevere)",
    date='1646-10-10',medium='muro',size='4 x 2',caption_year=1646,
    text="a' 10. ottobre 1646. seguì la coronazione della divina Madre, e del S. Bambino.",notes="Mother and Child crowned together."),
row('III',19,"Immagine di Maria Vergine nella Chiesa di S. Marcello","La Madonna in S. Marcello","Madonna dei Sette Dolori","S. Marcello al Corso","Rome, San Marcello al Corso",
    date='1695-04-17',medium='tela',size='10 x 7',caption_year=1695,
    text="supplicando per la corona, che fu lor consegnata a' 17. aprile 1695., e nel dì medesimo seguì la coronazione",
    notes="Venerated 'sotto l'Immagine de' dolori'; a miracle of November 1692 preceded the petition."),
row('III',23,"La Madonna di S. Maria ad Martyres ossia la Rotonda","La Madonna della Rotonda","Madonna","S. Maria ad Martyres (Pantheon)","Rome, Pantheon (Santa Maria ad Martyres)",
    date='1652-09-08',decree='1652',medium='tavola',size='5 x 3',caption_year=1652,
    text="mossero i Canonici di quella Collegiata a far istanza per la corona nel 1652. ... Scelse il Capitolo vaticano un dì memorabile per compiacer la richiesta; e mandò la corona agli 8. settembre dell'anno stesso."),
row('III',35,"La Madonna della Sanità in S. Lorenzo in Lucina","La Madonna della Sanità sopra l'Altare Maggiore in S. Lorenzo e Lucina",
    "Madonna della Sanità","S. Lorenzo in Lucina, altare maggiore","Rome, San Lorenzo in Lucina",
    date='1648',medium='muro',size='4 x 4',caption_year=1648,
    text="Il pubblico testimonio della corona fu dal Rmo Capitolo offerto alla divina Signora e al Santo Bambino nel 1648.",
    notes="Briccolani calls it 'della Salute'."),
row('III',41,"La Madonna del Rifugio in S. Lorenzo in Lucina","La Madonna nella Cappella del Purgatorio in S. Lorenzo e Lucina",
    "Madonna del Rifugio","S. Lorenzo in Lucina, cappella del Purgatorio","Rome, San Lorenzo in Lucina (Madonna delle Grazie)",
    date='1678-07-28',medium='muro',size='4 x 4',caption_year=1678,
    text="il Rev. Capitolo a' 28. luglio del 1678. offerse le corone d'oro a Lei, e al divin Figliuolo.",
    notes="Discovered on 24 July 1651. Briccolani lists it as 'delle Grazie'."),
row('III',45,"La Madonna delle Grazie, o del Suffragio nella Chiesa de' SS. Vincenzo, ed Anastasio a Trevi","La Madonna delle Grazie o del Suffragio in SS. Vinc. ed Anastasio a Trevi",
    "Madonna delle Grazie o del Suffragio","SS. Vincenzo e Anastasio a Trevi","Rome, Santi Vincenzo e Anastasio a Trevi",
    date='1679-03-13',decree='1679',medium='muro',size='3 x 2',caption_year=1679,
    text="La corona d'oro, a petizion de' Religiosi, le fu data nel 1679., e a' 13. di marzo dell'anno indicato seguì con divota pompa la coronazione."),
row('III',51,"La Madonna di S. Domenico, e Sisto","La Madonna in SS. Domenico e Sisto","Madonna","SS. Domenico e Sisto (monache di S. Sisto)","Rome, monastery of the Dominican nuns of San Sisto (Santi Domenico e Sisto, Magnanapoli)",
    date='1641',medium='tavola',size='3½ x 2',caption_year=1641,
    text="ben si dovea la corona d'oro, che le donò l'Illustre Capitolo vaticano l'anno 1641.",
    notes="Balzamo 2023 gives 14 January 1641. The nuns moved from S. Sisto vecchio in 1575 and into the new church on 30 July 1640."),
row('III',59,"La Madonna delle Grotte in S. Domenico, e Sisto","La Madonna delle Grotte nel Coro di sopra de' SS. Domenico e Sisto",
    "Madonna delle Grotte","SS. Domenico e Sisto, coro superiore","Rome, Santi Domenico e Sisto (Magnanapoli), inner monastery",
    date='1647',medium='muro',size='4 x 2',caption_year=1647,
    text="l'illustre Capitolo vaticano la coronò nel 1647.",
    notes="Found in a grotto of the old S. Sisto in 1570 and removed on 20 September 1577."),
row('III',65,"La Madonna nella Chiesa di S. Rocco","La Madonna nella Chiesa di S. Rocco","Madonna","S. Rocco a Ripetta","Rome, San Rocco a Ripetta",
    date='1658-01-21',decree='1654',medium='muro',size='3 x 2',caption_year=1658,
    text="fecero istanza per lo fregio della corona nel 1654. Il reverendo Capitolo non solo condiscese alla richiesta, donando le corone a' 21. di gennaro 1658., ma ... conserva nelle stanze capitolari una copia di questa Madonna col Santo Bambino",
    notes="The Chapter keeps a painted copy 'nelle stanze capitolari' — the series later catalogued by Zander/Magister."),
row('III',71,"La Madonna delle Grazie in S. Celso, e Giuliano in Banchi","La Madonna in S. Celso e Giuliano in Banchi","Madonna delle Grazie","SS. Celso e Giuliano in Banchi","Rome, Santi Celso e Giuliano",
    date='1665-05-17',medium='legno',size='6 x 4',caption_year=1665,
    text="Gl'Illmi Canonici di S. Pietro per supplica della rispettabile Collegiata, fregiarono delle corone Maria, e il divin Figliuolo a' 17. maggio 1665."),
row('III',73,"La Madonna di S. Pantaleo","La Madonna nella Chiesa di S. Pantaleo delle Scuole Pie","Madonna","S. Pantaleo (Scuole Pie)","Rome, San Pantaleo",
    date='1694-03-25',medium='tela',size='3 x 2',caption_year=1694,
    text="le corone, che furon date a Gianfrancesco di S. Pietro lor Generale a' 25. di marzo 1694.",
    notes="The day is the dossier's (Madonne coronate IV). Given to the church by legal instrument of donation on 4 December 1688."),
row('III',79,"La Madonna di S. Lorenzolo in Borgo vecchio","La Madonna in S. Lorenzo in Borgo","Madonna della Salute","S. Lorenzo in Borgo (Scuole Pie)","Rome, San Lorenzo in Borgo (Scuole Pie)",
    date='1696-12-06',decree='1696',deputies="due Canonici deputati",medium='muro',size='5 x 4',caption_year=1696,
    text="a' 6. decembre 1696. fece eseguire la coronazione alla presenza di due Canonici deputati. Il titolo consolante di questa Effigie detta della Salute ..."),
row('III',83,"La Madonna nella Chiesa della Maddalena de' Ministri degl'Infermi","La Madonna nella Chiesa della Madalena de PP. Ministri delli Infermi",
    "Madonna","S. Maria Maddalena (Ministri degli Infermi)","Rome, Santa Maria Maddalena",
    date='1668',cost='162.50',medium='tavola',size='4 x 3',caption_year=None,
    text="ne ottennero la coronazione nel 1668. Impiegò il reverendo Capitolo per le due corone la somma di scudi 162. 50.",
    notes="Two crowns, Mother and Child. The plate's year is cut off in the scan. Briccolani calls it 'della Salute'."),
row('III',87,"S. Maria in Trivio a Fontana di Trevi","S. Maria in Trivio alli Crociferi","Madonna (Immacolata Concezione)","S. Maria in Trivio (Crociferi)","Rome, Santa Maria in Trivio (Crociferi)",
    date='1677-05-29',medium='tavola',size='3½ x 2½',caption_year=1677,
    text="Il dì 29. maggio 1677. seguì la coronazione di quest'antichissima, e memorabile Imagine di Maria."),
row('III',93,"La Madonna della Purità nella Chiesa de' RR. Caudatari in Borgo","La Madonna della Purità in Borgo nuovo","Madonna della Purità","S. Maria della Purità in Borgo (Caudatari)","Rome, Santa Maria della Purità in Borgo",
    date='1646-04-16',medium='muro',size='4 x 3',caption_year=1646,
    text="Si fecer le istanze per la corona d'oro, che nell'anno 1646 a' 16. aprile l'Illustrissimo Capitolo vaticano ragionevolmente le offerse."),
row('III',97,"La Madonna di Costantinopoli","La Madonna di Costantinopoli","Madonna di Costantinopoli","S. Maria di Costantinopoli (Siciliani), a Capo le Case","Rome, Santa Maria di Costantinopoli a Capo le Case",
    date='1651-01-26',decree='1649',medium='tavola',size='3 x 2',caption_year=1651,
    text="quando nel 1649. fecer supplica per la corona. Il rapporto convalidato da testimonj con giuramento si conserva nell'archivio de' Canonici, i quali a' 26. gennaro 1651. condiscesero alla richiesta, e consegnarono la corona, della quale lo stesso giorno fu solennemente fregiata"),
row('III',105,"La Madonna delle Monache di S. Ambrogio","La Madonna nella Chiesa delle Monache di S. Ambrogio","Madonna","S. Ambrogio della Massima (monache)","Rome, Sant'Ambrogio della Massima",
    date='1674',medium='tavola',size='4 x 3',caption_year=1674,
    text="Per supplica delle Madri all'Illustrissimo Capitolo vaticano, fu decorata della corona l'anno 1674."),
row('III',109,"La Madonna delle Grazie in S. Paolo alla Regola","La Madonna in S. Paolo alla Regola","Madonna delle Grazie","S. Paolo alla Regola (Terz'Ordine, Siciliani)","Rome, San Paolino alla Regola",
    date='1651',cost='130',medium='muro',size='7 x 4',caption_year=1651,
    text="il reverendo Capitolo nel 1651. impiegò sc. 130 per le corone a Gesù, ed a Maria delle Grazie.",
    notes="Sources cited: 'MM. SS. del Capitolo vatic.'"),
row('III',113,"La SS. Vergine del Rosario nella Chiesa della Minerva","La Madonna del Rosario alla Minerva","Madonna del Rosario","S. Maria sopra Minerva, cappella del Rosario","Rome, Santa Maria sopra Minerva",
    date='1644-08-28',child='1654-12-15',cost='213',medium='tavola',size='7 x 5',caption_year=1640,
    text="que' Religiosi furono i primi a chieder la corona alla loro Imagine. Il Capitolo a' 28. di agosto 1644. vi condiscese colla spesa di 213. scudi. Nell'anno 1654. i Signori Canonici decretarono la corona al Santo Bambino, e celebrossi questa seconda coronazione a' 15. decembre dell'anno stesso.",
    notes="The notice says 28 August 1644 and calls the Dominicans the first to petition after the legacy; the plate says 1640, as does Briccolani. Left as the notice gives it."),
row('III',119,"La Madonna sopra l'Altar maggiore in S. Giacomo Scossacavalli","La Madonna su l'Altar Maggiore in S. Giacomo Scossacavalli","Madonna","S. Giacomo Scossacavalli","Rome, San Giacomo Scossacavalli",
    date='1664',medium='muro',size='5 x 3',caption_year=1664,
    text="La coronazione seguì con solennità nel 1664.",
    notes="Carried to S. Giacomo on 29 June 1662 after a dispute with the Chapter, which wanted it in the Vatican Basilica."),
row('III',127,"La Madonna dell'Orto","La Madonna del Orto","Madonna dell'Orto","S. Maria dell'Orto","Rome, Santa Maria dell'Orto",
    date='1657-08-19',decree='1657',medium='muro',size='6 x 5',caption_year=1657,
    text="Nel 1657. i Custodi della Chiesa porser supplica per la corona alla Divina Madre, e al S. Bambino. A' 19. di agosto dell'anno stesso furono pienamente compiaciuti"),
row('III',135,"Santa Maria del Suffragio","La Madonna del Suffraggio","Madonna del Suffragio","S. Maria del Suffragio","Rome, Santa Maria del Suffragio",
    date='1666',decree='1666-01-11',cost='117.20',medium='tavola',size='5 x 4',caption_year=1666,
    text="I Canonici vaticani dopo le consuete legali formalità, nel 1666. 11. gennaro accordarono la grazia. I Fratelli, affin di celebrare con magnificenza il sagro rito, eseguiron la coronazione qualche tempo dappoi. Le due corone a Gesù, e Maria ascesero al valore di sc. 117. 20."),
row('III',137,"La Madonna delle Grazie in S. Biagio della Pagnotta","La Madonna in S. Biagio della pagnotta","Madonna delle Grazie","S. Biagio della Pagnotta","Rome, San Biagio della Pagnotta",
    date='1671-01-31',deputies="due Canonici",medium='muro',size='4 x 3',caption_year=1671,
    text="il Capitolo vaticano, il quale per mezzo di due Canonici offerse le corone a Gesù, e a Maria a 31. gennaro 1671."),
row('III',141,"La Madonna della Quercia","La Madonna della Quercia","Madonna della Quercia","S. Maria della Quercia (Università dei Macellari)","Rome, Santa Maria della Quercia",
    date='1670',medium='tavola',size='6 x 3',caption_year=1670,
    text="Il Reverendo Capitolo vaticano autenticò la celebrità del culto, e delle grazie con la corona, che le offerse l'anno 1670."),
row('III',147,"La Madonna del Rimedio in S. Dionigi alle quattro Fontane","La Madonna in S. Dionisio alle quattro Fontane","Madonna del Rimedio","S. Dionigi alle Quattro Fontane (Trinitari)","Rome, San Dionigi alle Quattro Fontane",
    date='1667-09-07',medium='tela',size='5 x 4',caption_year=1667,
    text="A' 7. settembre 1667. ebber le corone per Gesù, e per Maria, e nel dì stesso seguì la coronazione (1). — (1) MM.SS. del Capitolo."),
row('III',155,"La Madonna degli Angeli in S. Lucia della Tinta","La Madonna in S. Lucia della Tinta","Madonna degli Angeli","S. Lucia della Tinta (Cocchieri)","Rome, Santa Lucia della Tinta",
    date=None,medium='muro',size='9 x 7',caption_year=None,text=None,
    notes="The notice gives no date, and the plate's caption was left unfinished: 'Coronata dal R.mo Capitolo di S. Pietro in Vatic. nel 16'. Briccolani gives 1667."),
row('III',161,"La Madonna di Monserrato","La Madonna nella Chiesa di Monserrato in Roma","Madonna di Monserrato","S. Maria di Monserrato (Spagnoli)","Rome, Santa Maria di Monserrato",
    date='1656-04-08',cost='120+',medium='marmo',size='7',caption_year=1656,
    text="impiegarono cenventi, e più scudi per coronare la Madre divina, e il divin Figliuolo. Cadde l'esecuzione agli 8. di aprile del 1656."),
# ---------------------------------------------------------------- Tomo IV (14 notices; the sixteen of the Appendice are 'non coronate')
row('IV',1,"La Statua della Pietà nella Basilica Vaticana","La Madonna della Pietà nella Basilica Vatic.","Madonna della Pietà","Basilica Vaticana (Pietà di Michelangelo)","Rome, Vatican Basilica (Pietà)",
    date='1637-08-31',cost='564',medium='marmo',size='12',caption_year=1637,
    text="il Conte Sforza a' 31. agosto 1637. fece coronare il divoto simolacro di Maria addolorata, che ha in seno il morto divin figliuolo. La corona fu di ben inteso lavoro, e del prezzo di scudi 564."),
row('IV',5,"Madonna della SS. Annunziata in Torre di Specchi","SS.ma Anunziata nella Chiesa di Tor di Specchi","Madonna Annunziata","Tor de' Specchi (Oblate di S. Francesca Romana), chiesa","Rome, Tor de' Specchi",
    date='1635-12-30',cost='150',medium='tela',size='14 x 7',caption_year=1635,
    text="egli stesso lo Sforza a' 30. decembre 1635. impiegò la somma di sc. 150. per coronare l'Annunziata delle oblate di Tor di Specchi",
    notes="Sforza's will names it expressly among the images to be crowned first."),
row('IV',9,"Imagine di Maria nella Chiesa antica di Tor di Specchi","La Madonna nel Monastero di Tor di Specchi","Madonna","Tor de' Specchi, chiesa antica interiore","Rome, Tor de' Specchi (monastery)",
    date='1687-06-17',deputies="Canonici Mattei e Ricci",medium='muro',size='9 x 4',caption_year=1687,
    text="Condiscese il Capitolo vaticano; e il 17. Giugno 1687. seguì la funzione alla presenza de' Canonici Mattei, e Ricci."),
row('IV',13,"Madonna del Carmine nella Chiesa di S. Grisogono","La Madonna in S. Grisogono","Madonna del Carmine","S. Crisogono in Trastevere","Rome, San Crisogono",
    date='1662-10-07',decree='1662',deputies="Mario Maffei Decano e Bernardino Casali",medium='mosaico',size='9 x 6',caption_year=1662,
    text="Il Reverendo Capitolo a' 7. ottobre 1662. per mezzo di due Deputati, Mario Maffei Decano, e Bernardino Casali fece la legal consegnazione delle corone a' detti Signori, e al P. Emilio Boino Prior del Convento. Così nell'istromento rogato dall'Abinante."),
row('IV',19,"Madonna nella Chiesa delle Monache Teresiane alle quattro Fontane","La Madonna in S. Teresa alle quattro Font.","Madonna","S. Teresa alle Quattro Fontane (Carmelitane)","Rome, Santa Teresa alle Quattro Fontane",
    date='1638-09-16',medium='tela',size='14 x 7',caption_year=1638,
    text="nel 1638 il giorno sedici settembre il pio Istitutore delle corone il Conte Alessandro volle fregiare questa divota effigie di ricca corona, che oltrapassa il peso di dieci once.",
    notes="Crowned by Count Sforza himself; the crown weighed over ten ounces."),
row('IV',25,"Madonna della Misericordia in S. Giovan Decollato","La Madonna in S. Gio. Decollato","Madonna della Misericordia","S. Giovanni Decollato","Rome, San Giovanni Decollato",
    date='1661-11-06',medium='muro',size='6 x 4',caption_year=1661,
    text="Il Reverendo Capitolo condiscese alle loro istanze, e diè lor le Corone per la divina Madre, e per Gesù Bambino. Seguì la coronazione a 6. Novembre 1661.",
    notes="The confraternity's papers 'si conservano nell'archivio capitolare di San Pietro n. 5'."),
row('IV',29,"Madonna del Rosario nell'Ospizio Apostolico degli Invalidi di Ripa","La Mad.a nella Chiesa di S. Michele a Ripa grande","Madonna del Rosario","S. Michele a Ripa Grande (Ospizio Apostolico)","Rome, San Michele a Ripa",
    date='1668-07-06',decree='1668-03-14',cost='131.90',medium='tela',size='9 x 4',caption_year=1668,
    text="a supplicare per la corona nel 1668. Il ven. Capitolo, esaminata la supplica, e trovatala ragionevole, a' 14. marzo del predetto anno segnò la grazia, e a 6. luglio fu eseguita con pubblico istromento. Il prezzo della corona fu di Sc. 131. 90."),
row('IV',35,"Madonna di S. Adriano a Campo Vaccino","La Madonna delle Grazie in S. Adriano","Madonna delle Grazie","S. Adriano al Foro (Mercedari)","Rome, Sant'Adriano al Foro",
    date='1677-12-01',medium='muro',size=None,caption_year=1677,
    text="i Sig. Canonici Vaticani contraddistinser con le corone Gesù e Maria, a tenor della supplica de' Religiosi della mercede. La coronazione seguì il dì 1. decembre 1677.",
    notes="Uncovered on 7 April 1589. The two crowns were stolen on 26 November 1769 and recovered in Naples."),
row('IV',45,"Madonna degli Angeli in S. Agata de' Tessitori","La Mad.a degl'Angioli in S. Aga.ta de Tessito.ri","Madonna degli Angeli","S. Agata dei Tessitori","Rome, Sant'Agata dei Tessitori",
    date='1729-07-31',medium='muro',size='8 x 6',caption_year=1729,
    text="il Capitolo Vaticano, attesa la supplica, e la pienissima relazione de' miracoli presentata dalla Compagnia de' Tessitori, a' 31. luglio 1729. consegnò loro le solite corone d'oro.",
    notes="Earlier crowned with silver crowns, then with gold ones given by a devotee, before the Chapter's."),
row('IV',50,"Madonna di S. Salvatore alle Coppelle","La Madonna in S. Salvatore delle Copelle","Madonna","S. Salvatore alle Coppelle","Rome, San Salvatore alle Coppelle",
    date='1675',deputies="Canonici Ludovico Palagi e Giulio Ricci",medium='muro',size='3 x 2',caption_year=1675,
    text="Nel 1675. i Canonici Ludovico Palagi, e Giulio Ricci recarono il tributo a Maria, e nella loro presenza seguì la coronazione con le consuete formalità."),
row('IV',53,"Madonna di S. Maria in Monterone","S. Maria in Monterone","Madonna","S. Maria in Monterone","Rome, Santa Maria in Monterone",
    date='1676-05-06',deputies="due Deputati del Capitolo",medium='tela',size='4 x 2',caption_year=1676,
    text="La corona d'oro per le istanze ben esaminate da due Deputati del Capitolo, furono offerte a Gesù, ed a Maria a' 6. maggio 1676."),
row('IV',57,"Madonna in S. Lucia del Gonfalone","La Madonna in S. Lucia del Confalone","Madonna","S. Lucia del Gonfalone","Rome, Santa Lucia del Gonfalone",
    date='1666-04-30',decree='1666-01-11',medium='tavola',size='6 x 4',caption_year=1666,
    text="So dall'archivio capitolar di S. Pietro che agli 11. di Gennaro del 1666 fu data a' Signori Canonici la supplica per le corone, che a' 30. di aprile furon consegnate per la divina Madre, e pel S. Bambino, che nel dì medesimo seguì con pompa, ed applauso de' divoti la coronazione."),
row('IV',61,"Madonna nella interior Cappella di S. Ignazio al Gesù","La Madonna nelle Cappellette di S. Ignazio al Gesù","Madonna","Chiesa del Gesù, cappellette di S. Ignazio","Rome, Chiesa del Gesù (Stanze di Sant'Ignazio)",
    date='1676-03-03',decree='1675-12-02',deputies="Canonici Giulio Ricci e Ludovico Palagi",medium='tela',size='4 x 3',caption_year=1676,
    text="Il Capitolo a' 2. decembre 1675. decretò che i Canonici Palagi, e Ricci ne facesser visita, e relazione. Il rapporto fu favorevole; onde a' tre di Marzo dell'anno accanto gli stessi Canonici Giulio Ricci, e Ludovico Palagi recarono alle cappellette del Gesù il dono a Maria, ed al Santo Bambino"),
row('IV',67,"Immagine di Maria Vergine nella Congregazione prima primaria del Collegio Romano","La Madonna nel Oratorio della Primaprimaria del Collegio Romano",
    "Madonna","Collegio Romano, Congregazione Prima Primaria (SS. Annunziata)","Rome, Collegio Romano (Prima Primaria)",
    date='1765-05',decree='1765-04-24',deputies="Card. Enrico Duca di York; Canonici Petrucci e Marcolini; notaio Lorenzini",medium='muro',size='3 x 2',caption_year=1765,
    text="A' 24. Aprile del 1765. si ottenne la grazia dal Reverendissimo Capitolo. Nel mese di Maggio, in un Sabato precedente alla funzione fu riccamente adornata la Congregazione ... La mattina della seguente Domenica venne S. A. R. Ema il Cardinale denominato Duca di York in Collegio Romano ... Fu rogato nelle forme l'atto della consegnazione della corona pel Notaro Lorenzini.",
    notes="Crowned on a Sunday in May 1765 by Cardinal Henry Benedict Stuart, Duke of York; the inscription in the oratory dates the Chapter's decree 26 July 1762."),
]
rows=[]
for n,r in enumerate(ROWS,1):
    m=re.match(r'(\d{4})',str(r['coronation_date'] or r['concession_date'] or ''))
    rows.append({'no':n,**r,'year':int(m.group(1)) if m else None})
assert len(rows)==74, len(rows)
out={'source':("[Pietro Bombelli, incisore], Raccolta delle immagini della Beatissima Vergine ornate della corona d'oro dal R.mo "
  "Capitolo di S. Pietro, con una breve ed esatta notizia di ciascuna immagine, 4 tomi, Roma, Salomoni, 1792 (plates dated "
  "1791-1793). Tomi II-IV: 74 of the 104 crowned images."),
 'scan':{'II':'https://archive.org/details/bub_gb_JhP2LAUmGjUC','III':'https://archive.org/details/bub_gb_rHbfIRvNjxkC',
         'IV':'https://archive.org/details/bub_gb_9vADu01fhEAC','I':'not found online'},
 'transcribed':'2026-09-14, from the OCR text with every date and number checked against the page image, and every plate caption read from the scan',
 'note':("One row per notice. `coronation_date` is the day the notice gives for the ceremony (or, where it names only the "
  "delivery of the crowns, that day); `concession_date` the decree or petition where given; `child_date` a separate crown "
  "for the Bambino Gesù. `caption_year`, `medium` and `size_palmi` are read from the engraved caption of the facing plate "
  "('in Tavola, Alta Pal. 4, Lar. 3, Coronata dal R.mo Capitolo di S. Pietro in Vatic. nel 1655'). `crown_cost_scudi` and "
  "`deputies` are as the notice gives them. `locality` is in the catalogue's own form so that Bombelli's image meets "
  "Briccolani's; `title` is the devotional title alone, the church being carried by `church_or_place`. Where the plate and "
  "the notice disagree on the year (Vittoria, Sole, Minerva, Prassede) the notice's date is kept and the disagreement noted."),
 'row_count':len(rows),'rows':rows}
json.dump(out,open(REPO/'data/bombelli-1792-raccolta.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
import collections
print('rows',len(rows),'with day',sum(1 for r in rows if r['coronation_date'] and len(r['coronation_date'])==10),
      'children',sum(1 for r in rows if r['child_date']),'costs',sum(1 for r in rows if r['crown_cost_scudi']),
      'undated',[r['title'] for r in rows if not r['coronation_date']])
print(collections.Counter(r['tomo'] for r in rows), collections.Counter(r['medium'] for r in rows))
